source 'https://rubygems.org'
#ruby '1.9.3'
ruby '2.1.5'
gem 'data_mapper'
gem 'dm-mysql-adapter'
gem 'dm-postgres-adapter'
gem 'dm-aggregates'
gem 'dm-is-read_only'
gem 'sinatra', :require => ['sinatra/base', 'sinatra/reloader', 'sinatra/multi_route']
gem 'sinatra-contrib'
gem 'json'
gem 'thin'
gem 'pg'
